### ISSUE TITLE
How to create log groups back after removing them?

### ISSUE THREAD

**Issue by gtennis** [horike37/serverless-delete-loggroups#3]
After running sls remove logs, all logs groups are removed and logging doesn't work anymore (obvious). But shouldn't they be recreated after running sls deploy again? Otherwise I need to remove and create the whole stack. Anyway, nice plugin!

**Comment by horike37** [comment]
Thank you for using this plugin @gtennis!
 
>But shouldn't they be recreated after running sls deploy again?

This behavior is not bug, by design. Since v1.6, all logs groups have been generated by sls core via CloudFormation. The purpose I made this plugins is to delete all logs groups that was generated automatically by Lambda executing before v1.5. Otherwise, `sls deploy` fail to conflict with old logs groups when upgrading v1.6
